# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-16 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20170816_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='host_user_binds',
        ),
    ]
