# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-16 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_remove_task_host_user_binds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='result',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '成功'), (1, '失败'), (2, '超时'), (3, '初始化')]),
        ),
    ]
